# Generated by Django 4.0.5 on 2022-06-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
