# Generated by Django 4.0.5 on 2022-06-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
