# Generated by Django 4.0.5 on 2022-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('account', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
