# Generated by Django 4.0.5 on 2022-06-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorMovie',
            new_name='Actor_Movie',
        ),
    ]
