# Generated by Django 4.0.5 on 2022-06-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_actor_movie_movieactor_alter_movieactor_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='running_time',
            new_name='running_time_min',
        ),
    ]
