# Generated by Django 4.0.5 on 2022-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_running_time_movie_running_time_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='movies.actor'),
        ),
        migrations.DeleteModel(
            name='MovieActor',
        ),
    ]
