# Generated by Django 4.0.5 on 2022-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_actor_delete_movieactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(db_table='movie_actor', to='movies.actor'),
        ),
    ]
